### ISSUE TITLE
NTR: stotting

### ISSUE THREAD

**Issue by diatomsRcool** [obo-behavior/behavior-ontology#108]
For new term requests, please provide the following information:

## Preferred term label

stotting

## Synonyms

pronking
pronging

## Textual definition

a pursuit deterrence behavior of quadripeds in which they spring into the air, lifting all four feet off the ground simultaneously with the legs held in a relatively stiff position.
## Suggested parent term

predator avoidance behavior

## Attribution

http://orcid.org/0000-0002-2908-332

**Comment by matentzn** [comment]
@diatomsRcool Have you added terms to NBO before? It should be no problem to add these yourself if you don't want to wake - I don't think there will be much objections.

**Comment by diatomsRcool** [comment]
I don't think so....

**Comment by matentzn** [comment]
You definitely have an ID range!
https://github.com/obo-behavior/behavior-ontology/blob/fc4ea0a93763f07471d7b4344b9286504b2531c8/src/ontology/nbo-idranges.owl#L39

Do you want to try add this in Protege, and making a pull request? Just make sure the id is in your ID space, and not used yet!

**Comment by aclark-binghamton-edu** [comment]
@DitchingIt 1. there is still plenty of contention about what stotting does for an individual, but we ended up calling it display.  It is not protective in-and-of-itself, but only if it leads to assessment and avoidance by a predator. As a behavior, it also occurs in play of ungulates.  And whether the behavior in some species also serves to warn others is not off the table.  
2. For the definition, I would NOT build protective behavior into it and the definition proposed does well for gazelles but not so well for e.g. white tailed deer and some others, e.g, Patagonian maras (a rodent, Dolichotis patagonium).  Here is a more general or more encompassing suggestion by Barrows 2001(the  Dictionary again) "an individual's display involving a conspicuous, stiff-legged, bounding gait with its tail raised and white rump flashing"  I might suggest we be careful about the white rump.  Not sure every species that stotts has one!  
3. here is a reference, although I haven't yet checked Caro's 1988 definition in this paper--there are other refs therein.  Fritz Walther in 1948, 1966 papers discussed it earlier.
         Caro, 1988
The functions of stotting: a review of the hypotheses
    [Animal Behaviour](https://www.sciencedirect.com/journal/animal-behaviour)
[Volume 34, Issue 3](https://www.sciencedirect.com/journal/animal-behaviour/vol/34/issue/3), June 1986, Pages 649-662
https://doi.org/10.1016/S0003-3472(86)80051-3
 4. Pronking is a synonym.

**Comment by DitchingIt** [comment]
@aclark-binghamton-edu @diatomsRcool

1. How about as a child of NBO:0020077 display condition (to predator)?
2. Barrows definition seems fine to me. 
3. If you can quote or double check Caro for the definition content,  or we can reference Barrows directly. 

NB: I've ordered myself Barrows 3rd Ed as a birthday present, so will be on your wavelength soon!

**Comment by aclark-binghamton-edu** [comment]
Checking Caro and will suggest the solution.
Happy Birthday--a 3rd edition will put you ahead of my 2nd edition!

**Comment by DitchingIt** [comment]
@aclark-binghamton-edu Just tidying up loose ends and wondering if you have made progress checking Caro and can suggest a solution?

**Comment by aclark-binghamton-edu** [comment]
I will try to tidy that one up for you/nbo tonight. Busy week and leading nature hikes for Earth day today. Sent from my iPhoneOn Apr 22, 2023, at 11:52 AM, Ditch Townsend ***@***.***> wrote:﻿
@aclark-binghamton-edu Just tidying up loose ends and wondering if you have made progress checking Caro and can suggest a solution?

**Comment by DitchingIt** [comment]
@aclark-binghamton-edu Hope it goes well!

**Comment by aclark-binghamton-edu** [comment]
@DitchingIt Ok--have re-read Caro's paper.  I can attach the pdf for your interest/records, but wrt the above:  he first states:  "Stotting (named by Percival 1928) is a common kind of jumping seen in many species of Cervidae, Antilocapridae and Bovidae (see Byers 1984)",  gives Walther's comprehensive and detailed description for Thompson's gazelles and then says this about interspecific and interdefinitional variation: "Other authors provide similar definitions; the essential features of stotting are taking all four legs off the ground simultaneously and holding the legs stiff and straight."  And in this now-old paper, he stresses we don't have enough data to test most hypotheses but says that it is reasonable to think that the meaning is "predator detected" and quite probably signalling to the predator "you been seen".  So placement as a child of display condition (to predator) is still  an hypothesis tho' probably as strong one.  A broader placement might be simply under "Display-visual" because it can be a display of:  "you are seen", or "I am a bad choice of prey", or "there's a cheetah over there" (as understood by conspecifics) or even "Look here chase me" by mothers of fawns.  That seems to be the message of Caro 1986 Animal Behaviour.
