### ISSUE TITLE
obsolete: behavioral control of excretion

### ISSUE THREAD

**Issue by cmungall** [obo-behavior/behavior-ontology#115]
GO is obsoleting excretion:

https://github.com/geneontology/go-ontology/issues/22368

NBO has a term "behavioral control of excretion". GO believes excretion is not a useful grouping, so this NBO concept should be replaced by more specific terms:

http://purl.obolibrary.org/obo/NBO_0000038

**Comment by DitchingIt** [comment]
For now, I suggest only elevating defecation and urination by one level, so they are still emission behaviors.

**Comment by rays22** [comment]
I would like to raise an objection to obsoleting [NBO:0000038 behavioral control of excretion](https://www.ebi.ac.uk/ols/ontologies/NBO/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNBO_0000038).
It is a [behavior](https://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0007610) that applies to animals according to the text definition of [GO:0007610.](https://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0007610).
1. When watching cats, dogs or birds, I see some instinctive excretion-related behavioural patterns. I suspect these are behavioural processes that are under strong selection pressure in evolution and related phenotypes do exist. If you wish I can also look up some evidence in the literature.
2. Moreover, the physiological process of [defecation](https://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0030421) and the removal of nitrogenous waste via urine have a shared route via the [cloaca](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0000162) in many vertebrates.
Is there any evidence that the [behavioral control of defecation](https://www.ebi.ac.uk/ols/ontologies/nbo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNBO_0000039&lang=en&viewMode=All&siblings=false) is always a separate process form the [behavioral control of urination](https://www.ebi.ac.uk/ols/ontologies/nbo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNBO_0000040&lang=en&viewMode=All&siblings=false) in amhibians or reptiles?
Here is an [instance of a closely spaced lizard excretion product](https://en.wikipedia.org/wiki/Excretion#/media/File:Feces_and_uric-acid.jpg) that suggests a coordinated [behavioral control of excretion](https://www.ebi.ac.uk/ols/ontologies/NBO/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNBO_0000038).

It is unfortunate that GO intends to obsoletes a useful physiological process category without a proper physiological ontology term replacement, but NBO should not drop a useful term because of that.
I suggest we drop the [NBO:0000038](https://www.ebi.ac.uk/ols/ontologies/nbo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNBO_0000038&lang=en&viewMode=All&siblings=false) EQ axiom in the defintion that uses [GO:0007588 excretion](https://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0007588) for now and replace it once an appropriate physiological ontology term emerges.

**Comment by DitchingIt** [comment]
@rays22 @sbello Excellent point and I will try to do as you have suggested. I will return either with an amended PR or a question about how to do it.
