### ISSUE TITLE
Suggestions for visual pursuit 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [obo-behavior/behavior-ontology#12]
```
ID: NBO:0000446
Preferred Name : visual pursuit
Definitions: Selectively track a moving object. [NBO:GVG]


1. Definition needs to include mention of vision.  Current term applies to bats 
using echolocation.
2. Needs to be subclass of visual behavior
3. Should not be a subclass of eye movement - as not all animals that can 
visually track can move their eyes.

General question: 
This is under body part movement - should visual pursuit be treated more 
generally, encompassing tracking via whole body movement.


```

Original issue reported on code.google.com by `dosu...@gmail.com` on 24 Feb 2013 at 8:48

**Comment by DitchingIt** [comment]
1. I suggest a simple addition to the definition which has a visual element: "selective tracking that follows a moving object by eye". It also allows a future echolocation-related corollary to be added.
2. I agree and propose moving it.
3. Currently this class is no longer a subclass of eye movement but a direct child of body part movement. GENERAL Q: I agree with moving it out of body part movement because 'pursuit' is not a body part (see 2 above). But I think the same criticism would apply to suggesting it was about whole body movement, as for some relatively sessile animals it is only about eye movement; for others it is about head movement. Whether it is about body, neck, or eye muscle movement however, it still comes down to positioning the eyes relative to the subject. So long as eye movement is defined to include any mode of eye movement (and there is currently no definition at all), I think visual pursuit could be a subclass of eye movement. Indeed, a new term 'visual search' could be added as a sibling to 'visual pursuit' using exactly the same kinesthetic modality to connect to things like active foraging behavior. This could form a new issue, but I don't propose to add visual pursuit back under eye movement just now.

@aclark-binghamton-edu @dosumis @pmidford Does anyone disagree?

**Comment by aclark-binghamton-edu** [comment]
@DitchingIt 
OK --certainly adding "by eye" makes good sense.
Second we are using "eye movement" in two ways:  eyes can move themselves, independent of everything else (main category Movement--subcategory "of eyes");  eyes can BE moved by the use of other body parts or even by relocating the whole body directionally.  So given that I think everyone agrees on these two options, we should not restrict visual pursuit to the use of one vs the other.  Both ways to move the eyes could be separately listed as options under eye movement (or movement of the eyes).  
But visual pursuit (which isn't different than we would mean by visual tracking, is it???)  is indeed best under "Body Part Movement"--given that eyes or some other body part will be moved.   I agree that some parallel terms for echolocational tracking are needed. And in fact, audio-tracking and olfactory tracking would be good, because ear movements, nose movements/inhalations or head movements facilitate those. 

Maybe we need a term like "Sensory Tracking" as opposed to whole-body tracking
I like adding Visual Search, especially as that sometimes has some neurologically interesting patterns. 

Maybe these ideas have just made this incredibly confusing!

**Comment by DitchingIt** [comment]
Not confusing - sounds great, but better for a future NTR. Just now I'm focused on tidying up very old items and won't connect it to either body part or whole.
