### ISSUE TITLE
A behaviour model to rebuild the NBO on

### ISSUE THREAD

**Issue by DitchingIt** [obo-behavior/behavior-ontology#126]
Here is my proposal for a behaviour model on which to rebuild the NBO (see #124). It is based on an amalgamation of an idea published in October 2022 and one from 2008.

[NBO proposal 230118.pdf](https://github.com/obo-behavior/behavior-ontology/files/10451397/NBO.proposal.230118.pdf)

I think there are three options in response:
1. NO (because...)
2. YES (but here are some comments...)
3. ALTERNATIVE (peer reviewed source...)

**Comment by cmungall** [comment]
Thanks for this well thought out document.

I like the way you have laid out the opportunities/challenges:

1. It needs clear ownership, even if it is operating in an open way, or it will be difficult to track accountability and make decisions.
2. It needs to develop and uniformly implement a reasonably comprehensive style and convention guide, rooted in OBO principles and guidelines.
3. **It needs a model structure potentially incorporating all behaviour processes, which makes biological sense even if there is not a full consensus, and is consistent with an axiomatic approach**
4. It needs to refocus, because its two branches (processes and phenotypes) are pulling strongly in different directions.
5. It needs a consistent rewrite of many labels, definitions and annotations.
6. It needs a much more fully saturated set of terminal (leaf) classes.
7. It needs a valid cross-referencing system.
8. It needs a revamp of its logical axioms.

I largely agree with all of these. I think the first is the most challenging. This ontology is functionally inactive, and I think it should be declared as such on the OBO site to be fully transparent (Nico has made much-welcome technical changes but there has been no content changes in years). There simply seems to be a lack of people willing commit effort to this project, and no funding on the horizon.

Your document responds to 3. I'm not qualified to comment on the theoretical underpinnings. There are others semi-active here like @pmidford, @dosumis, and @mellybelly who can comment on how this aligns with current theoretical underpinnings in ethology, model organism behavioral genetics, and clinical research. As a generalist, I would caution that whatever ontological or theoretical commitments are made, that these should be broadly understandable in order to make it easier for multiple people to maintain the ontology, and for annotators to use it.

I can think of multiple ontologies where experienced ontology developers created a structure that adhered strongly to a rigorous well-accepted theory, but this led to ontology structures that were hard to maintain confusing to use by annotators, leading to inconsistent population of annotations, and too brittle to generalize. This may not apply to your model, this is just a general note of caution.

I would say that any revamp of NBO should driven as much by requirements than by theory. Perhaps the next step is to have a virtual workshop bringing together different stakeholders to outline what they need from a behavior ontology (or ontologies). This may be possible to do under the auspices of the Phenomics First project and the current OBO phenotype group (cc @dosumis).

I'm not totally sure how to respond to your 1/2/3 choice, and what the implications are. I do think that with any ontology, legacy or otherwise, and incremental approach often works best. This might entail encoding some of your model as DOSDPs, mapping existing terms to this structure, making small PRs changing the structure while demonstrating the benefits of the proposed model structure. Or it may be the case that you think a more radical overhaul is necessary -- in which case I would encourage you to go for it!

**Comment by DitchingIt** [comment]
Thanks @cmungall for some really helpful comments. First off, I plan to simplify the model by pruning one of its dimensions. As to commitment, this is my current number one project and if anything, I am likely to try to do too much too fast!

**Comment by pmidford** [comment]
Ditch - I've read your proposal and I agree with most or all of the ontology related issues you raise.  Before I comment on your model proposal, I've going through the Mallpress and Aunger&Curtis papers to get some more background.

**Comment by DitchingIt** [comment]
> Ditch - I've read your proposal and I agree with most or all of the ontology related issues you raise. Before I comment on your model proposal, I've going through the Mallpress and Aunger&Curtis papers to get some more background.

@pmidford I took a hint from @cmungall and plan to prune the model back to just a two dimensional, outcome approach, based on Mallpress alone, or it could be too complicated for anyone to use. I like how the ABO had two groups of behavior and I think we can reflect that to some extent in the model v2. I'll see what I can come up with this weekend - hopefully by the end of next week at least. Please orientate yourself to the two papers in anticipation, and maybe @aclark-binghamton-edu will have time to too. I wouldn't be surprised if Aunger & Curtis partly stimulated the existing domain structure, but only someone who knew could say.

**Comment by DitchingIt** [comment]
@pmidford @aclark-binghamton-edu Attached is my second version behaviour model based on Mallpress alone. Hopefully it makes sense.Feedback from anyone appreciated.

**Comment by aclark-binghamton-edu** [comment]
@DitchingIt could you please give me full reference for Mallpress--I am not sure I have it.

**Comment by aclark-binghamton-edu** [comment]
Also I can report that Aunger & Curtis is an interesting take on behavior categorization, but definitely was not the ABO background.  Our first draft from a workshop of animal behaviorists (model organisms under represented) was in 2004, and the plan to provide portals where behavioral data could be found through metadata searches began shortly after 2001.

**Comment by DitchingIt** [comment]
@aclark-binghamton-edu Thanks for the background on ABO. The Mallpress reference is: Mallpress DE. Towards a functional classification of behaviour: a taxonomy based on outcomes. Adaptive Behavior. 2022;30(5):417–50.

**Comment by aclark-binghamton-edu** [comment]
@DitchingIt   thanks--have it now. will review quickly and be ready to discuss your ideas in proposal.

**Comment by DitchingIt** [comment]
## Physiology in the model
I thought I'd link to some discussions happening elsewhere about this so we don't lose them:

1. [Do we want mechanistic definitions?](https://github.com/obo-behavior/behavior-ontology/issues/123#issuecomment-1384376946)
2. [Is behavioral exhaustion NBO:0000472 a behaviour?](https://github.com/orgs/obo-behavior/teams/behavior-ontologies/discussions/1/comments/12)
3. Is sleeping a [phenotype ](https://github.com/orgs/obo-behavior/teams/behavior-ontologies/discussions/1/comments/8)or a [behaviour](https://github.com/orgs/obo-behavior/teams/behavior-ontologies/discussions/1/comments/13)?

**Comment by DitchingIt** [comment]
1. Using an Outcome based model (based on Mallpress) hasn't gained any traction.
2. I suspect that anything but a one dimensional model will not be simple enough for potential users.

I will close this issue and maybe explore another type of model in another issue before throwing in the towel. @cmungall may be right about the need to declare the NBO 'functionally inactive' but I'd like to keep trying for a while first.

**Comment by matentzn** [comment]
You are doing a great job. In other news, discussing what a disease is has taken 10 years, with no results, many broken friendships and nothing but scorn :P This here is going.. great.
