### ISSUE TITLE
Ethology module - Upper levels

### ISSUE THREAD

**Issue by DitchingIt** [obo-behavior/behavior-ontology#184]
## Proposals
I am pleased to begin offering my proposals to revamp the core of the NBO. This core module is broadly focused on Ethology, with minimal curation relating to reflexes, learning, memory, or 'intelligence'. The first offering is of 10 classes at the highest levels. Please find your way to a [Google Sheet](https://docs.google.com/spreadsheets/d/1aH4BAY-2gMWlLA-GdUlPv0fQs0lwXkoSTnfPZY62P_Y/edit?usp=sharing) I have prepared in a ROBOT template. Anyone with the link has permission (and encouragement) to add comments to it, but a mention here will enliven the discussion.

Of general note:

- Almost any ID starting NBO:007.... is newly proposed and will not be found in the NBO files
- Highlit boxes contain changes
- The **Definition Source** column is for readers ease; the ontologically important column is the Definition Xref
- The **Notes** column will be for public view
- Ours is probably the first ontology to use the new **Synonym Type** option which can track **Prior Labels** alongside other types of synonym
- I understand that you will need to use an editor like Protege to view the **Remark** column, which contains comments more pertinent to viewers like you
- The **See Also** column contains OBO Xrefs which may be more or less appropriate, without being an exact **Xref**
- The **Allow annotation** column picks up a redundant issue which may become pertinent in future if the ontology is used to support annotations. Either way, where it exists it should hopefully encourage new term requests for subclasses.

Of specific note:
- [A different discussion](https://github.com/obo-behavior/behavior-ontology/issues/101#issuecomment-779184219) needs to take place about what to do with our top class NBO:0000313 behavior process which for now will be disconnected from everything here except NBO:0070005 fitness behavior
- This module is partially notional: ignoring the label NBO:0000607 cognitive behavior here for example will not make it disappear from NBO or sever its connection with NBO:0000313 behavior process, i.e. the only things that will actually change are things in the ROBOT template

## Background
Many questions will be answered (or generated) by first reading my [background paper](https://github.com/obo-behavior/behavior-ontology/files/12275174/Ethology.module.pdf) to this proposal. Thinking continues to evolve, not least the deeper into things I go, so there may be some changes to the exact structure I proposed there, but it represents the thrust, for which this (and future) ROBOT sheets add the detail.

To track or contribute to the eventual disposition of more disparate elements (outside this module) feel free to follow [Phenotypes](https://github.com/orgs/obo-behavior/projects/1/views/5) and Humans #157.

## Curation
To the degree possible, all edits should follow the #122 NBO Styles and Conventions for which a [reference sheet](https://github.com/obo-behavior/behavior-ontology/files/12214578/Conventions.230731.pdf) exists.

No obsoletions should occur directly as a result of this Issue. However, I would like to use the ROBOT sheet (edited in the light of this discussion) to generate a pull request which will include the (non-obsoletion) changes discussed.

Note that each ROBOT row regenerates (i.e. wipes and rewrites) current NBO data for that ID, so if you don't see something in a line that you think should be there, please say, even if a new column has to be created to accomodate it. NB: Other comments on the ROBOT template are also welcome but I will probably have to refer them on for resolution as it was not my creation.

The NBO is currently community-run (i.e. unfunded). Proposals about curation outside of the use-cases implied by this Ethology module are most likely to be acted upon if accompanied with offers to curate them.

**Comment by DitchingIt** [comment]
@aclark-binghamton-edu @pmidford @dosumis @jannahastings @matentzn @obo-behavior/behavior-ontologies
I hope to turn this into a PR in mid-September and would appreciate any perspectives.

**Comment by aclark-binghamton-edu** [comment]
@DitchingIt Whew--ok.  I may be alone in not having any up to date Protege running (comments not visible probably), but will review and try to offer thoughts before or in early September!  Also thinking about the "realizes/ses" issues. Thanks for your work.

**Comment by DitchingIt** [comment]
I have uploaded a revised [Google sheet](https://docs.google.com/spreadsheets/d/1tuOQytdZz9csynrJCxOjIX7-WtbA3XYNz-rvORz7vRU/edit?usp=sharing) taking into account comments added to the original. There is also uncertainty about #183 and I am seeking advice on whether I can disjoint classes in a different ontology.

**Comment by aclark-binghamton-edu** [comment]
@DitchingIt @pmidford @dosumis  I continue to appreciate these efforts and I have not completed my earlier-promised comments.  But I have just taken a look at the Google sheet and am quite worried that the definitions are in some cases not correct or confusing (e.g. evolutionary fitness behavior--which defines fitness purely at the level of populations and apparently absolute rates of increase rather than at the level of relative reproduction of individuals--something that at the very least is almost never demonstrable for behavior; but the reference isn't talking about individual fitness but "evolution of population mean fitness"--see below ) and similarly buys into a survival trait vs reproductive trait dichotomy. Definitions of some items e.g. social behavior deviate from the original in a way that makes the definition hard to understand or not meaningful. I emphasize that demonstrating the function and evolutionary significance of behaviors are two often separate steps in studying a given behavior...one may identify a function but not understand its significance in evolutionary terms--significance that can be varied depending on actor or context and include both reproduction and survival etc, so I am uncomfortable defining functional categories as falling under "types of fitness".  

I will try to make this clearer--and would appreciate thoughts from @pmidford.  

And as for Hendry et al and the definition of fitness--here is what that article is really about--taken from their abstract:

**The rate of evolution of population mean fitness informs how selection acting in contemporary populations can counteract environmental change and genetic degradation (mutation, gene flow, drift, recombination). This rate influences population increases (e.g., range expansion), population stability (e.g., cryptic eco-evolutionary dynamics), and population recovery (i.e., evolutionary rescue). We review approaches for estimating such rates, especially in wild populations**

**Comment by aclark-binghamton-edu** [comment]
Hi @DitchingIt!  I knew I was sounding too "hysterical".--sorry!  I will return in long form later today with fuller answers/suggestions.  The unresolved problems of fitness revolve around measures of fitness.  In some sense, we know exactly what it is--degree to which some entity propagates itself, to be completely vague!  So it is a property of "entities" which in this case, has to be individual organisms.  Our behavior terms all describe individual organisms--not genes or populations or cultures.  (GO term definitions might be said to describe something in between!) And to be "favored" or selected, our organism (in this case) must have high relative fitness, ie more propagation than another organism.  BUT the measures of fitness are always contentious and always wanting--we never know enough.  Is it sufficiently measured by surviving better to time x? or having lots of matings?  or lots of surviving offspring? or lots of grand-offspring? These are all proxies for some true assessment.   And for many described behaviors, we don't have a fitness assessment of any kind.  One of my (Confusing) points is that when we describe behaviors, we sometimes assume that they are discrete and contribute to relative fitness.  And yes I agree we can often suggest that it is survival and/or reproduction, but it is not just "or".  Often one cannot say "it is advantageous just because it contributes to survival"--for instance, being a sentinel is thought, in some instances, to primarily influence social attractiveness and reproduction.  So I was objecting to incorporating "survival" or "reproduction" into the definition of a class of behaviors.    I strongly suggest, where possible, to punt on these decisions and stick to what we can know.  We even stick our necks out when categorizing something as "anti-predator behavior".  

I am still probably being unclear and also not offering good solutions--for which I apologize.  I did sound much too reactive.  I will review what I said and your answer and clarify my recommendations with respect to specific table entries.  @pmidford might also have thoughts here.

**Comment by DitchingIt** [comment]
Hi again @aclark-binghamton-edu and others.

1. I can see that we will struggle right now to keep my highest level suggestion. Unless there is a viable alternative suggestion, I will drop **fitness behavior** for now. Would it be worthwhile adding a note to **NBO:0000313 behavior process** perhaps with the links to SIO:000357, APO:0000216, and WBPhenotype:0002118 ?
2. I appreciate the difficulty of choosing **survival** or **reproduction** as parent to a class:

- I recognise there is unlikely to be a simplistic meaning to your objection, but it may be worth pointing out to others that under the _genus-differentia_ construction, we must mention a parent in every definition
- We can include multiple parents in the definition; we need not get stuck on 'or' statements, otherwise we are doomed to repeat this problem at every sub-level, not just here. Using your example (although there might be a number of subclasses in between and so  **survival** or **reproduction** are just proxies), we could define **sentinel behavior** as something like _A survival behavior that provides socially attractive full-time vigilance to a full-time foraging group, potentially influencing its members reproductive behavior_. I want to leverage the power of an ontology: to my mind **sentinel behavior** isn't just a twig on a branch, but a node in a network
- Even if we are not sure, we can build it in if it has been reasonably suggested (preferably via a reference but I don't think we should exclude ingenuously argued opinions, and we can easily add subdivisions with slightly different labels)

**Comment by DitchingIt** [comment]
I've uploaded a [modified Google Sheet](https://docs.google.com/spreadsheets/d/1JrXIQvjsZaKlHmXxU94mYY1jgqYcgPT1Pf8k3TXGbbQ/edit?usp=sharing) with changes related to point 1 above.

**Comment by DitchingIt** [comment]
I've uploaded a modified Google sheet. It:removes the column for the 'characteristic of' object property (see #183).

**Comment by DitchingIt** [comment]
PR #189 merged.
