### ISSUE TITLE
Switch imports to local modules

### ISSUE THREAD

**Issue by dosumis** [obo-behavior/behavior-ontology#22]
Importing the whole of ChEBI is not useful.

```
<owl:Ontology rdf:about="&obo;behavior.owl">
    <oboInOwl:remark rdf:datatype="&xsd;string">2012-07-09</oboInOwl:remark>
    <owl:imports rdf:resource="&obo;chebi.owl"/>
```

...

**Comment by dosumis** [comment]
@cmungall - Job for one of your make files.  Do you have a standard one I can grab?

**Comment by cmungall** [comment]
It's actually kind of difficult to set up for the first time. It's very 
fragile, all the imports need to be in place to begin with, with correct 
IRIs

I'd take this opportunity to just switch to robot for the SLME 
extraction. You can still mix with owltools in the Makefile to do any 
upstream preprocessing

The main limitation of robot here is that expects the seed to be an 
ID/IRI list rather than an OWL file. So you need a script to make an ID 
list from the seed ontology. https://github.com/ontodev/robot/issues/44
