### ISSUE TITLE
Social Learning

### ISSUE THREAD

**Issue by GoogleCodeExporter** [obo-behavior/behavior-ontology#6]
```
The definition of social learning seems to limit it to humans.  However, there 
is a long history of study of social learning in animals (e.g., Zental and 
Galef 1988).  The definition should be updated to reflect this.
```

Original issue reported on code.google.com by `peter.mi...@gmail.com` on 10 Jun 2011 at 3:22

**Comment by reality** [comment]
Current definition doesn't seem to be limited to humans; peer groups can exist in non-human societies

**Comment by pmidford** [comment]
The problem here isn't that peer groups don't exist in non-human animals.  The problem is that limiting social learning to within peer groups is incorrect.  Restricting the term to peer groups suggests the definition comes from sociology or social psychology and deliberately excludes vertically transmitted social learning that goes by other terms when applied to humans.  In animal behavior social learning covers both vertical (e.g., parent to offspring) and horizontal (peer to peer) learning situations.  Since no term specific to vertical learning (and note that teaching is something different from social learning), there is no justification for the human specific limitation to peer-to-peer learning.

**Comment by DitchingIt** [comment]
@pmidford @dosumis @aclark-binghamton-edu 
- NBO currently makes 'social learning' a child of 'associative learning behavior'

- Wikipedia's [Social learning in animals](https://en.wikipedia.org/wiki/Social_learning_in_animals) page defines it as, "learning that is facilitated by observation of, or interaction with, another animal or its products"

I propose changing the NBO definition to, "associative learning behavior that arises from observing or interacting with another individual."

Any thoughts or are you okay with this?

**Comment by aclark-binghamton-edu** [comment]
@DitchingIt Not entirely or maybe I should say, not without expecting possible contention--as many definitions describe social learning, that phrase "facilitated by" can include opportunities for animal Y learning that x item is food because others are down on the ground and thus the would-be learner is reassured enough to come to the ground. Thus the association is NOT with the features of the item about which it is learning, just the context in which the individual can do its own learning.
 I am not sure whether all would agree that social learning has to fall UNDER Associative Learning.  But I am not a learning theorist and don't have dogs in these often semantic fights, and thus I guess it is ok.  I also cannot wrap my head around "learning behavior", whether social or associative...   

So-with that little diversionary preamble, as long as both are in NBO there in this way, the change in NBO definition is ok.
