### ISSUE TITLE
NTR: autotomy

### ISSUE THREAD

**Issue by GoogleCodeExporter** [obo-behavior/behavior-ontology#9]
```
http://en.wikipedia.org/wiki/Autotomy
```

Original issue reported on code.google.com by `cmung...@gmail.com` on 23 Apr 2012 at 9:04

**Comment by reality** [comment]
term request

**Comment by DitchingIt** [comment]
@aclark-binghamton-edu @pmidford @dosumis @reality 
I realised I sent a pull request without a chance for you to review my suggestions. I have converted the PR to draft for now. Any thoughts including a better source? The main points are:
## Definition 
protective behavior that sheds or discards an appendage or organ
## Source
Wikipedia

**Comment by aclark-binghamton-edu** [comment]
Barrows' entry interestingly does NOT specify "protective", gives a **broad** definition for individuals and colonies--and cites  Formanowicz (1990, Animal Behaviour) citation of Fabre 1928 (p400)--for its sense, not wording.  So both of his citations focused on arthropods.  Below is Barrows' definition; I can check Formanowicz.  Not sure I can access Fabre's book at this moment.  Barrows gives another ref that purportedly cites reviews--Matthews and Matthews 1978 Insect Behavior. Wiley.--p 341.  Don't have a copy but will look for a recent review.
Barrows:   "an animal's or colony's shedding of a part of its whole".

**Comment by DitchingIt** [comment]
1. [Maginnis](https://academic.oup.com/beheco/article/17/5/857/207107) notes that autotomy can relate to a 'fouled molt' in an arthropod as well as to 'predation avoidance'. However, they say both are forms of escape with survival benefits. Antipredation behavior is categorised in NBO as a subclass of **protective behavior** which is itself defined in terms of 'potential danger'. This is slightly different from the ABO functional classes in which antipredation took a top seat. The original ABO also listed autotomize as a behavioral act, which I like. But we have not yet begun to discuss restructuring the NBO into acts and functions; for now, I want to get autotomy back into the picture in the best available place. As a sibling of antipredation behavior within the existing structure, I think we allow that it is more than antipredation, but as a child of protective behavior, we acknowledge for now that it is about survival (i.e. self-defense in the face of a danger), and we leave restructuring for another day.
2. Regarding the definition, I'm not sure where to go with the idea of shedding part of a colony. Early work involving hydrozoans involved colonies, and I can see this applying in Cnidarians. In that sense they are operating as a single organism and I could willingly exchange the word organism for individual/animal in an autotomy definition. But should we include sting autotomy in a honeybee which kills the individual but benefits the hive, or the amputation of part of an ant nest which happens to kill some larvae to prevent flooding in the rest of the nest but protects other larvae? Is a hive or a nest also a colony? I'm wary of allowing a superorganism to creep into our definition. Would you be willing for us to source Barrows as follows: **protective behavior that sheds part of an organism**? Perhaps we even need to write 'an integral part' or 'a functional part' to avoid overlap with grooming?

**Comment by aclark-binghamton-edu** [comment]
I agree with most of your points including that autotomy of a "caught" leg in an exoskeleton molt or a caught leg in a crevass or a leg entangled in a spider's web are all reasonably included, as all events are "adaptive", have survival value  to that individual, and also rely on selected mechanisms to lose the caught appendage quickly with minimal damage.  So--
1.  **I am OK on making it a sib of antipredation behavior--under Protective Behavior ( for now, although clearly it seems to be both half sib and twin.** 
2. Definition:  I would like to use Barrow's slight rewording to make it clearly an active behavior of the organism--to read something like  "An animal's self-protective shedding of a body part, especially appendage (sensu Barrows and Maginnis both).  I am also OK at this point leaving out _shedding or loss of parts of colonies so as to protect the whole; parts including all or part of the individual colonial organisms that make it up_  ...although what we appreciate about "organisms" at this point can turn that into hair-splitting!   But I think it is ok for our purposes here that the mechanism and decision and benefit all lie within the same unit and willingness to be sacrificed is not included.  
3.  We might hopefully get to behaviors that do have that super-organismal function and can include "autotomy" of some sort there.  IF so, we can add a "see xxx for protective/adaptive loss of parts of colonial organisms."

I will add that Protective Behavior is a vague term I do not love--because there is confusion between self-protection, survival oriented behavior and behavior that intercedes for another organism or even territory/burrow/etc.  Those seem divergent at a higher level.  But that fight can be fought later!

Thanks for all your attention to these issues!

**Comment by DitchingIt** [comment]
@aclark-binghamton-edu Okay. On an axiomatic note, I don't think the way the ontology is structured will really enable us to use a term like 'especially' in the definition, but I can add something in a comment.
